php_version: '8.1'

rules:
    composer.dependencies_not_installable:
        enabled: false
    web.apache_config:
        enabled: false
    web.missing_favicon:
        enabled: false
    web.missing_web_manifest:
        enabled: false

working_directory: 'back'
