name: Continuous Integration

on:
    push:
        branches:
            - develop
            - main
    pull_request: ~

jobs:
    back-rector:
        name: "Back / Rector"
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.0'
                    tools: composer:v2

            -   name: Install dependencies
                working-directory: ./back
                run: composer install --prefer-dist --no-progress --no-suggest

            -   name: Rector
                working-directory: ./back
                run: composer rector -- --dry-run

    back-phpcsfixer:
        name: "Back / PHP CS fixer"
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.0'
                    tools: composer:v2

            -   name: Install dependencies
                working-directory: ./back
                run: composer install --prefer-dist --no-progress --no-suggest

            -   name: PHP CS Fixer
                working-directory: ./back
                run: composer cs -- --dry-run

    front-lint:
        name: "Front / Lint"
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   uses: actions/setup-node@v2
                with:
                    node-version: 16

            -   name: Install dependencies
                working-directory: ./front
                run: npm ci

            -   name: Lint
                working-directory: ./front
                run: npm run lint
